[terminal]
shell = "/bin/zsh"

[window]
opacity = 0.9
blur = true


[font]
normal = {family= "FiraCode Nerd Font"}

[general]
import = [
    "~/.config/alacritty/themes/themes/ayu_mirage.toml"
]

[env]
TERM = "xterm-256color"
